swagger: '2.0'
info:
  version: 1.0.0
  title: Project api sample
  description: |
    #### Project API description example
host: localfund.happynetwork.org
basePath: "/project/api"

tags:
- name: "fund"
  description: "Local Fund"
schemes:
  - https
  - http

paths:
  /fund/act:
    get:
      tags:
        - fund
      summary: "Get total funds and projects"
      parameters:
        - name: year
          in: query
          type: string
        - name: zone
          in: query
          type: string
        - name: prov
          in: query
          type: string
        - name: dist
          in: query
          type: string
        - name: fund
          in: query
          type: string
      responses:
        '200':
          description: Return activity number
          schema:
            $ref: '#/definitions/Activity'

definitions:
  Activity:
    type: object
    properties:
      zonecode:
        type: string
        description: Zone code
      zonename:
        type: string
        description: Zone name
      year:
        type: number
        description: Year of activity
      fund:
        type: number
        description: Number of fund
      project:
        type: number
        description: Number of activity