<?php
global $url_list;

$url_list = [
	['http://wintesla2003.com','rss/counter/day/'],
	['https://rap3gshop.com','rss/counter/day/'],
	'-',
	['https://nathoncity.com', 'rss/counter/day/'],
	['https://sdtc.go.th', 'rss/counter/day/'],
	['https://softganz.com', 'rss/counter/day/'],
	['https://softganz.com/meeped', 'rss/counter/day/'],
	'-',
	['https://ahsouth.com', 'rss/counter/day/'],
	['https://communeinfo.com', 'rss/counter/day/'],
	['https://consumersongkhla.org', 'rss/counter/day/'],
	['https://consumersouth.com', 'rss/counter/day/'],
	['https://hatyaicityclimate.org', 'rss/counter/day/'],
	['https://lanhoiseab.com', 'rss/counter/day/'],
	['https://scccrn.org', NULL],
	['https://scccrn.com', NULL],
	['https://scf.or.th', 'rss/counter/day/'],
	['https://songkhlahealth.org', 'rss/counter/day/'],
	['https://workersaving.org', 'rss/counter/day/'],
	'-',
	['https://consumersouth.org', 'rss/counter/day/'],
	['https://dekthaikamsai.com', 'rss/counter/day/'],
	['https://followpts.yru.ac.th', 'rss/counter/day/'],
	['https://hednetwork.com', 'rss/counter/day/'],
	['https://happynetwork.org', 'rss/counter/day/'],
	['https://mehealthpromotion.com', 'rss/counter/day/'],
	['https://nfcnetwork.org', 'rss/counter/day/'],
	['https://nxtgenhedb.com', 'rss/counter/day/'],
	['https://pathailand.com', 'rss/counter/day/'],
	'-',
	['https://sator4u.com', 'rss/counter/day/'],
	'-',
	['https://abcg.icarsmile.com', 'rss/counter/day/'],
	['https://icarsmile.com', 'rss/counter/day/'],
	['https://meesystem.com', 'rss/counter/day/'],
	['https://siamfibreboard-sfm.com', 'rss/counter/day/'],
	['https://theagendasouth.com', 'rss/counter/day/'],
	'-',
	['https://1t1u.psu.ac.th', 'rss/counter/day/'],
	['https://alumni.medicine.psu.ac.th', 'rss/counter/day/'],
	['https://localfund.happynetwork.org', 'rss/counter/day/'],
	['https://ppi.psu.ac.th', 'rss/counter/day/'],
	['https://suvarnabhumi.psu.ac.th', 'rss/counter/day/'],
	['http://www.nadrec.psu.ac.th', 'rss/counter/day/'],
	['http://www.southwarning.com', 'rss/counter/day/'],
	'-',
	['https://9mee.com', NULL],
	['https://bookgang.net', 'rss/counter/day/'],
	['https://manoch.net', 'rss/counter/day/'],
	['https://sdtn.in.th', 'rss/counter/day/'],
	'-',
	['9me.name', NULL],
	['nampha.com', NULL],
	['nampha.name', NULL],
	['nineme.com', NULL],
	['numpha.name', NULL],
	['tonnum.name', NULL],
	'-',
	['https://asiamuseum.co.th', NULL],
	['https://banbanradio.com', NULL],
	['beneaththewings.com', NULL],
	['https://dlfp.in.th', NULL],
	['https://fmlc8.go.th', NULL],
	['gardenhomehotel.com', NULL],
	['hatyai.mobi', NULL],
	['https://healthyradio.org', NULL],
	['https://healthytv.org', NULL],
	['mmmglobaltorich.com',NULL],
	['neer19.com', NULL],
	['phumeelife.com', NULL],
	['psuheartcenter.com', NULL],
	['raktalaethai.com', NULL],
	['https://ranodhospital.go.th', NULL],
	['roypeesadao.com', NULL],
	['rubberparnet.org', NULL],
	['satunwatch.org', NULL],
	['siamsolidwood.com', NULL],
	['songkhlalakeinfo.com', NULL],
	['songkhlamediaforum.com', NULL],
	['southnurse.com', NULL],
	['srubberwatch.org', NULL],
	['suvarnabhumi.name', NULL],
	['talcreative.co.th', NULL],
	['xraypsu.com', NULL],
	['thaiichr.org', NULL],
	['https://thebeachkohkood.com', NULL],
	['https://volunteerpsu.com', NULL],
	['https://winteslashop.com',NULL],
	'-',
	['678easy2pay.com', NULL],
	['chalaehealthycharter.com', NULL],
	['epay4net.com', NULL],
	['k-boxshop.com',NULL],
	['khlong-u-taphao.com', NULL, NULL], // 'rss.php?counter&day='],
	['knokmobile.com', NULL],
	['krisanakhaokor.com', NULL],
	['napradu.go.th', NULL],
	['plaikhaophatthalung.com', NULL],
	['ruraldoctor.or.th', NULL],
	['sadao-education.com', NULL],
	['seewithsound.com', NULL],
	['slbact.org', NULL],
	['smartgrowththailand.com', NULL],
	['songkhlafc.net', NULL],
	['talesabsongkhla.com', NULL],
	['watersatun.com', NULL],
	['samatchachumphon.org', NULL],
	['tambonkohtaew.go.th', NULL],
	['tambonprik.go.th', NULL],
	['thaisouthtoday.com', NULL, NULL], // 'rss.php?counter&day='],
	['tonprik.org', NULL],
];
?>